# Número de processos worker (auto = 1 por CPU disponível)
worker_processes auto;

events {
    # Máximo de conexões simultâneas por worker
    worker_connections 1024;
}

http {

    # upstream define o servidor de destino das requisições
    # "cinema-api" é o apelido que usaremos no proxy_pass
    # "api" é o nome do serviço no docker-compose, porta 8080
    upstream cinema-api {
        server api:8080;
    }

    server {
        # Nginx escuta na porta 80
        listen 80;
        server_name localhost;

        location / {
            # Encaminha todas as requisições para a API Spring Boot
            proxy_pass http://cinema-api;

            # Repassa headers importantes para a API saber a origem real
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}